[package]
name = "tiktoken-rs"
version = "0.5.1"
description = "Library for encoding and decoding with the tiktoken library in Rust"
rust-version = "1.57.0"
include = ["assets/**/*", "src/**/*", "README.md"]
edition.workspace = true
keywords.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
license.workspace = true
readme = "../README.md"

[dependencies]
anyhow = "1.0.71"
async-openai = { version = "0.13.0", optional = true }
base64 = "0.21.2"
bstr = "1.5.0"
fancy-regex = "0.11.0"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
pyo3 = { version = "0.19.0", optional = true }
rustc-hash = "1.1.0"

[features]
python = ["dep:pyo3"] # build python bindings
async-openai = ["dep:async-openai"]
