[package]
name = "tiktoken-rs"
version = "0.2.0"
description = "Library for encoding and decoding with the tiktoken library in Rust"
rust-version = "1.57.0"
edition.workspace = true
keywords.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "../README.md"
docs = "https://docs.rs/tiktoken_rs"

[dependencies]
anyhow = "1.0.68"
base64 = "0.21.0"
bstr = "1.2.0"
fancy-regex = "0.11.0"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
pyo3 = "0.18.1"
rustc-hash = "1.1.0"
