[package]
name = "tiktoken-rs"
version = "0.5.3"
description = "Library for encoding and decoding with the tiktoken library in Rust"
rust-version = "1.72.0"
include = ["assets/**/*", "src/**/*", "README.md"]
edition.workspace = true
keywords.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
license.workspace = true
readme = "../README.md"

[dependencies]
anyhow = "1.0.75"
async-openai = { version = "0.14.0", optional = true }
base64 = "0.21.3"
bstr = "0.2.17"
fancy-regex = "0.11.0"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
pyo3 = { version = "0.19.2", optional = true }
rmp-serde = "1.1.2"
rustc-hash = "1.1.0"
serde = { version = "1.0", features = ["derive"] }

[features]
python = ["dep:pyo3"] # build python bindings
async-openai = ["dep:async-openai"]
