[package]
name = "tiktoken-rs"
version = "0.3.2"
description = "Library for encoding and decoding with the tiktoken library in Rust"
rust-version = "1.57.0"
edition.workspace = true
keywords.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "../README.md"

[dependencies]
anyhow = "1.0.69"
async-openai = "0.10.0"
base64 = "0.21.0"
bstr = "1.3.0"
fancy-regex = "0.11.0"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
pyo3 = { version = "0.18.1", optional = true }
rustc-hash = "1.1.0"

[features]
python = ["dep:pyo3"] # build python bindings
